# 1.1 - Numpy  (Numerical Python)

**[Documentación](https://numpy.org/doc/stable/)**

**[Código fuente](https://github.com/numpy/numpy)**


![numpy](images/numpy.png)

NumPy es el paquete fundamental para computación cientifíca en python. Es una librería de python nos permite manejar vectores, matrices, [tensores](https://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial) (arrays multidimensionales) y además realizar todas las operaciones matemáticas y lógicas de los mismos, como la manipulación de la dimensión, ordenado, selección, I/O, operaciones estadísticas, transformadas de Fourier, simulación aleatoria y un largo etcétera. Constituye la herramienta de álgebra lineal.

## Recordatorio de álgebra

+ Contenidos:

    + Concepto de tensor
    + Operaciones con vectores
        + Concepto de espacio vectorial y base
        + Suma de vectores
        + Producto escalar
        + Producto vectorial
    + Operaciones con matrices
        + Suma de matrices
        + Producto matricial
        + Matriz Identidad
        + Matriz Traspuesta (Hermítica)
        + Matriz Inversa 
        + Determinate

### Tensor

La palabra ['tensor'](https://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial) se utiliza a menudo como abreviatura de campo tensorial, que es un valor tensorial definido en cada punto en una variedad. El primero en utilizar esta palabra fue William Rowan Hamilton en 1846, empleándola para lo que actualmente se conoce como módulo y fue Woldemar Voigt en 1899 quien la empleó en su acepción actual. La palabra tensor proviene del latín tensus, participio pasado de tendere 'estirar, extender'. El nombre se extendió porque la teoría de la elasticidad fue una de las primeras aplicaciones físicas donde se usaron tensores. Gregorio Ricci-Curbastro en 1890 desarrolló la notación actual con el nombre de geometría diferencial absoluta, y se popularizó con la publicación de Cálculo Diferencial Absoluto de Tullio Levi-Civita en 1900. Con la introducción de la teoría de la relatividad general por parte de Albert Einstein alrededor de 1915 se encontró su aplicación más pragmática. La Relatividad General es netamente tensorial. Einstein había aprendido del mismo Levi-Civita el uso de tensores con gran dificultad.

Podemos pensar en un tensor como la generalización del ente algebraico. Con un ejemplo se verá más claro.

Un **número**, cualquier número, $2$, $3.6$, $\pi$, $\phi$, $\sqrt{2}$, es un **tensor de rango $0$**.

Un **vector**, cualquier vector, sea como sea su longitud, $(1, 2, 3)$, $(0, 5, 2, 1, 5)$, $(9,2)$, es un **tensor de rango $1$**.

Una **matriz**, cualquier matriz, sean cuales sean sus dimensiones, es un **tensor de rango $2$**.

Un **cubo de Rubik** por ejemplo es un **tensor de rango $3$**.

Pensar en dimensiones superiores es complicado por no decir imposible, pero se pueden interpretar a través del contenido. Una **bolsa llena de cubos de Rubik** es un **tensor de rango $4$**.

Una **caja llena de bolsas que están llenas de cubos de Rubik es un tensor de rango $5$**.

Y así sucesivamente.

### Operaciones con vectores

**Espacio vectorial**

La definición matemática de [espacio vectorial](https://es.wikipedia.org/wiki/Espacio_vectorial) implica los conceptos de conjunto, ley de composición(operación) interna y ley de composición externa, definida sobre un segundo conjunto. Resumiendo, un espacio vectorial es una estructura creada sobre un conjunto no vacío con ambas leyes de composición. A los elementos de un espacio vectorial se les llama vectores.

Veamos un ejemplo:

Un espacio vectorial es el espacio tridimensional ${\Bbb R}^{3}$. Los elementos de ${\Bbb R}^{3}$ son vectores, por lo que la ley de composición interna es la suma de vectores. Para la ley de composición externa se necesita otro conjunto, que en esta caso son los números reales ${\Bbb R}$, y queda definida como el producto por escalares, multiplicar un vector por un número.



**Base vectorial**

Una [base](https://es.wikipedia.org/wiki/Base_(%C3%A1lgebra)) es un conjunto de vectores {$v_{1}, v_{2}, v_{3}, ... ,v_{n}$} que cumplen las siguientes propiedades:

+ Todos los elementos de la base pertenecen al mismo espacio vectorial.
+ Los elementos de la base forman un sistema linealmente independiente (ninguno es combinación lineal de los demás).
+ Cualquier elemento del espacio vectorial se puede escribir como combinación lineal de los elementos de la base (es lo que se llama sistema generador del espacio vectorial).

Ejemplo:

En ${\Bbb R}^{3}$, la base principal (llamada canónica) es {$(1,0,0), (0,1,0), (0,0,1)$}. Todos esos vectores pertenecen a ${\Bbb R}^{3}$, son linealmente independientes(ninguno puede ser una suma de los otros) y cualquier otro vector en ${\Bbb R}^{3}$ se puede representar como una suma de esos tres, una combinación lineal. No es única, otra base de ${\Bbb R}^{3}$ podría ser {$(1,1,1), (1,1,0), (1,0,0)$}



**Suma de vectores**

Los vectores se suman por componentes, lo que implica que ambos tienen la misma longitud. Por ejemplo en ${\Bbb R}^{3}$:

$$\vec{A}=A_{x}\vec{i}+A_{y}\vec{j}+A_{z}\vec{k}$$

$$\vec{B}=B_{x}\vec{i}+B_{y}\vec{j}+B_{z}\vec{k}$$

$$\vec{A}+\vec{B}=(B_{x}+A_{x})\vec{i}+(B_{y}+A_{y})\vec{j}+(B_{z}+A_{z})\vec{k}$$

$$$$

$$\vec{A}=(1,8,9)$$

$$\vec{B}=(4,3,0)$$

$$\vec{A}+\vec{B}=(5,11,9)$$



**Producto escalar**

Hay que diferenciar entre producto por escalares, un número por un vector resultando un vector, y el productor escalar donde se multiplican dos vectores resultando un número, un escalar.

+ Producto por escalares:

Se realiza elemento a elemento la multiplicación por el número:

$$\vec{A}=(1,8,9)$$

$$2*\vec{A}=(2,16,18)$$

+ Productos escalar:

Se realiza multiplicando elemento un vector fila por un vector columna y sumando los resultados. Hay que tener en cuenta, igual que en la suma, que ambos vectores tienen el mismo número de elementos. También se le llama producto punto (dot product) o producto interno (inner product).

$$\vec{A}\cdot\vec{B}=(1, 8, 9)\cdot\begin{pmatrix}4\\3\\0\end{pmatrix} = 1·4+8·3+9·0 = 4+24+0 = 28$$



**Producto vectorial**

En este caso, se multiplican dos vectores resultando otro vector. La manera más fácil de hacerlo es a través de un determinante:


$$\vec{A}\times \vec{B} = \begin{vmatrix}
\hat{\imath}&\hat{\jmath}&\hat{k}\\
1 & 8 & 9 \\
4 & 3 & 0
\end{vmatrix} = \begin{vmatrix}
8 & 9 \\
3 & 0
\end{vmatrix}·\hat{\imath} - 
\begin{vmatrix}
1 & 9 \\
4 & 0
\end{vmatrix}·\hat{\jmath} +
\begin{vmatrix}
1 & 8 \\
4 & 3
\end{vmatrix}·\hat{k} = (8·0-9·3)·\hat{\imath}-(1·0-9·4)·\hat{\jmath}+(1·3-8·4)·\hat{k}$$

$$\vec{A}\times \vec{B} = (-27, 36, -29)$$

### Operaciones con matrices


**Suma de matrices**

Las matrices tienen definidas sus dimensiones sugún el número de filas($m$) y de columnas($n$), y se representan como $A_{mxn}$. Para sumar matrices las dimensiones tienen que ser las mismas, igual que ocurría con los vectores, y se realiza elemento a elemento (element wise):


$$\begin{pmatrix}
5 & 7 & 1 \\
4 & 0 & 2 
\end{pmatrix}+\begin{pmatrix}
0 & 0 & 3 \\
2 & 2 & 7 
\end{pmatrix}=\begin{pmatrix}
5 & 7 & 4 \\
6 & 2 & 9 
\end{pmatrix}$$



**Producto matricial**

Para multiplicar matrices tenemos que tener en cuenta las dimensiones, porque el producto matricial no es conmutativo e incluso a veces no se puede realizar. El número de columnas de la primera matriz tiene que ser igual que el número de filas de la segunda y el resultado tendrá el número de filas de la primera y el número de columnas de la segunda. Es decir:

$$A_{rxn}\cdot B_{nxq} = C_{rxq}$$


$$\begin{pmatrix}
5 & 7 & 1 \\
4 & 0 & 2 
\end{pmatrix}\cdot\begin{pmatrix}
0 & 0 \\
2 & 3 \\
2 & 7 
\end{pmatrix}=\begin{pmatrix}
5·0+7·2+1·2 & 5·0+7·3+1·7 \\
4·0+0·2+2·2 & 4·0+0·3+2·7
\end{pmatrix}=\begin{pmatrix}
18 & 28 \\
4 & 14
\end{pmatrix}$$



**Matriz Identidad**

Elemento neutro de la multiplicación, solo $1_s$ en la diagonal:

$$I = \begin{pmatrix}
1&0&\cdots&0&0\\
0&1&\cdots&0&0\\
\vdots&\vdots&\ddots&\vdots&\vdots\\
0&\cdots&\cdots&\cdots&0\\
0&0&\cdots&1&0\\
0&0&\cdots&0&1\\
\end{pmatrix}$$



**Matriz traspuesta  (hermítica)**

La traspuesta $A^{T}$ de una matriz $A$ puede ser obtenida reflejando los elementos a lo largo de su diagonal.

$$A=\begin{pmatrix}
5 & 7 & 9 \\
4 & 0 & 7 \\
1 & 2 & 2
\end{pmatrix}$$

$$A^{T}=\begin{pmatrix}
5 & 4 & 1 \\
7 & 0 & 2 \\
9 & 7 & 2
\end{pmatrix}$$


Se le dice hermítica si los elementos son números complejos, es la traspuesta conjugada (el conjugado de $x+iy$ es $x-iy$).


**Matriz Inversa**

¿Como se dividen las matrices? Se multiplica por la inversa. El cálculo de la matriz inversa es:

$$A= \begin{pmatrix}
       a_{11} & a_{12} \\ 
       a_{21} & a_{22}
    \end{pmatrix}$$
    
    
$$A^{-1}=\begin{pmatrix}
a_{11} & a_{12} \\ 
a_{21} & a_{22}
\end{pmatrix}^{-1}
=\frac{1}{\lvert A\rvert}
\begin{pmatrix}
a_{22} & -a_{12} \\ 
-a_{21} &  a_{11}
\end{pmatrix}$$


**Determinante**

$$A=\begin{pmatrix}
    1 & 3 & 2 & -6 \\ 
    0 & -1 & -4 & 1 \\ 
    0 & -2 & -6 & 3 \\ 
    0 & -2 & -10 & 3
  \end{pmatrix}$$
  

$$$$


$$det(A)=\begin{vmatrix}
    1 & 3 & 2 & -6 \\ 
    0 & -1 & -4 & 1 \\ 
    0 & -2 & -6 & 3 \\ 
    0 & -2 & -10 & 3
  \end{vmatrix}=\begin{vmatrix}
    1 & 0 & 0 \\ 
    -2 & 1 & 0 \\ 
    -2 & 0 & 1
  \end{vmatrix}\cdot
  \begin{vmatrix}
    1 & 4 & 1 \\ 
    2 & 6 & 3 \\ 
    2 & 10 & 3
  \end{vmatrix}=\begin{vmatrix}
    1 & 4 & 1 \\ 
    0 & -2 & 1 \\ 
    0 & 2 & 1
  \end{vmatrix}
  =
  \begin{vmatrix}
    -2 & 1 \\ 
    2 & 1
  \end{vmatrix}
  =-4$$
  
  

**Veamos algo de todo esto en python:**


**Arrays**

In [2]:
# importar libreria

import numpy as np

In [3]:
# vector, tensor rango 1

# números aleatorios distribuidos uniformemente entre 0 y 1

vector=np.random.random(5)

vector

array([0.54678057, 0.51186238, 0.35897858, 0.87783358, 0.30962156])

In [4]:
# matriz, tensor rango 2

matriz=np.random.random((5, 3))

matriz

array([[0.53740513, 0.99324031, 0.64198906],
       [0.85870556, 0.32392426, 0.49374409],
       [0.77147219, 0.92498922, 0.94697844],
       [0.06995627, 0.8218838 , 0.54538279],
       [0.03705467, 0.68975874, 0.20439685]])

In [5]:
# dimension

matriz.shape

(5, 3)

In [6]:
# numero de elementos

matriz.size

15

In [7]:
type(matriz)

numpy.ndarray

In [8]:
# primera fila de la matriz

matriz[0]

array([0.53740513, 0.99324031, 0.64198906])

In [9]:
matriz[0][1]   # segundo elemento de la primera fila

0.9932403053521435

In [10]:
# cubo, tensor rango 3

cubo=np.random.random((3, 2, 4))  # 3 capas, 2 filas, 4 columnas

cubo

array([[[0.42610842, 0.98530751, 0.6692604 , 0.77895539],
        [0.19829162, 0.6973127 , 0.86932865, 0.09866917]],

       [[0.65002127, 0.84035488, 0.8288467 , 0.52406832],
        [0.0262195 , 0.46723109, 0.88130489, 0.66279736]],

       [[0.08482248, 0.61569346, 0.88331939, 0.41970573],
        [0.43665368, 0.19702437, 0.38377241, 0.89721121]]])

In [11]:
# tensor rango 4

tensor=np.random.random((2,3,4,5))

tensor

array([[[[0.15254708, 0.86161629, 0.42642457, 0.4242238 , 0.74458476],
         [0.17703683, 0.70717005, 0.04372164, 0.91873625, 0.17466326],
         [0.60821613, 0.42239174, 0.0611186 , 0.46202651, 0.83553639],
         [0.0599899 , 0.24590111, 0.23053132, 0.67443503, 0.33118456]],

        [[0.47009135, 0.87662051, 0.27750996, 0.76019549, 0.71901058],
         [0.40534343, 0.46481257, 0.87630967, 0.56328823, 0.89514598],
         [0.81121947, 0.44076942, 0.70034629, 0.9510986 , 0.50204397],
         [0.08061183, 0.7836144 , 0.35443958, 0.91956043, 0.22594151]],

        [[0.4247396 , 0.55162161, 0.52143161, 0.4681097 , 0.87120162],
         [0.06154853, 0.44508564, 0.85091115, 0.20714582, 0.38523224],
         [0.30117679, 0.7012306 , 0.32212952, 0.86849452, 0.62793981],
         [0.33679849, 0.53123079, 0.99849769, 0.28767173, 0.45877786]]],


       [[[0.64325562, 0.98507473, 0.81415685, 0.85488936, 0.55765188],
         [0.51805462, 0.58541189, 0.78675342, 0.07776721, 0.10908368]

In [13]:
type(tensor)

numpy.ndarray

In [14]:
tensor[0]

array([[[0.15254708, 0.86161629, 0.42642457, 0.4242238 , 0.74458476],
        [0.17703683, 0.70717005, 0.04372164, 0.91873625, 0.17466326],
        [0.60821613, 0.42239174, 0.0611186 , 0.46202651, 0.83553639],
        [0.0599899 , 0.24590111, 0.23053132, 0.67443503, 0.33118456]],

       [[0.47009135, 0.87662051, 0.27750996, 0.76019549, 0.71901058],
        [0.40534343, 0.46481257, 0.87630967, 0.56328823, 0.89514598],
        [0.81121947, 0.44076942, 0.70034629, 0.9510986 , 0.50204397],
        [0.08061183, 0.7836144 , 0.35443958, 0.91956043, 0.22594151]],

       [[0.4247396 , 0.55162161, 0.52143161, 0.4681097 , 0.87120162],
        [0.06154853, 0.44508564, 0.85091115, 0.20714582, 0.38523224],
        [0.30117679, 0.7012306 , 0.32212952, 0.86849452, 0.62793981],
        [0.33679849, 0.53123079, 0.99849769, 0.28767173, 0.45877786]]])

In [15]:
tensor[0:1]

array([[[[0.15254708, 0.86161629, 0.42642457, 0.4242238 , 0.74458476],
         [0.17703683, 0.70717005, 0.04372164, 0.91873625, 0.17466326],
         [0.60821613, 0.42239174, 0.0611186 , 0.46202651, 0.83553639],
         [0.0599899 , 0.24590111, 0.23053132, 0.67443503, 0.33118456]],

        [[0.47009135, 0.87662051, 0.27750996, 0.76019549, 0.71901058],
         [0.40534343, 0.46481257, 0.87630967, 0.56328823, 0.89514598],
         [0.81121947, 0.44076942, 0.70034629, 0.9510986 , 0.50204397],
         [0.08061183, 0.7836144 , 0.35443958, 0.91956043, 0.22594151]],

        [[0.4247396 , 0.55162161, 0.52143161, 0.4681097 , 0.87120162],
         [0.06154853, 0.44508564, 0.85091115, 0.20714582, 0.38523224],
         [0.30117679, 0.7012306 , 0.32212952, 0.86849452, 0.62793981],
         [0.33679849, 0.53123079, 0.99849769, 0.28767173, 0.45877786]]]])

In [16]:
tensor[1,2]

array([[0.99817763, 0.16379105, 0.70724675, 0.51974499, 0.8420645 ],
       [0.40882496, 0.39333049, 0.86586873, 0.61369757, 0.38191024],
       [0.9273158 , 0.98691049, 0.32127868, 0.38599535, 0.90459138],
       [0.57992099, 0.93282964, 0.09026901, 0.84154242, 0.58777839]])

In [17]:
tensor[1,2, 3, 4]

0.5877783864261423

In [18]:
tensor[0, 0, -1, -1]

0.3311845623155225

In [19]:
# de listas a arrays
lst=[5,6,7]

array=np.array(lst)

array

array([5, 6, 7])

In [21]:
lst_lst=[[1,2,3], [4,5,6], [7,8,9]]

array=np.array(lst_lst)

array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
type(array)

numpy.ndarray

**Operaciones matemáticas**

In [23]:
100*matriz

array([[53.74051294, 99.32403054, 64.19890583],
       [85.87055641, 32.39242605, 49.37440903],
       [77.14721855, 92.49892244, 94.69784448],
       [ 6.99562664, 82.18837956, 54.53827931],
       [ 3.70546707, 68.97587379, 20.43968532]])

In [26]:
# suma de todos los elementos

matriz.sum()

8.860881379337721

In [28]:
sum(sum(matriz))

8.86088137933772

In [29]:
np.sum(matriz)

8.860881379337721

In [30]:
# suma por columnas

matriz.sum(axis=0)

array([2.27459382, 3.75379632, 2.83249124])

In [31]:
# suma por filas

matriz.sum(axis=1)

array([2.17263449, 1.67637391, 2.64343985, 1.43722286, 0.93121026])

In [32]:
np.sum(matriz, axis=1)

array([2.17263449, 1.67637391, 2.64343985, 1.43722286, 0.93121026])

In [33]:
# la matriz no es un tensor de rango 3

matriz.sum(axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [34]:
# el cubo si lo es
    
cubo.sum(axis=2)

array([[2.85963172, 1.86360214],
       [2.84329117, 2.03755283],
       [2.00354106, 1.91466167]])

In [35]:
tensor.shape

(2, 3, 4, 5)

In [37]:
# suma por bolsas

tensor.sum(axis=0).shape

(3, 4, 5)

In [38]:
# suma por capas del cubo

tensor.sum(axis=1).shape

(2, 4, 5)

In [39]:
# suma por filas

tensor.sum(axis=2).shape

(2, 3, 5)

In [40]:
# suma por columnas

tensor.sum(axis=3).shape

(2, 3, 4)

In [41]:
# minimo de toda la matriz

matriz.min()

0.037054670671455736

In [43]:
# maximo de cada columna

matriz.max(axis=0)

array([0.85870556, 0.99324031, 0.94697844])

In [44]:
# mediana de todos los elementos

np.median(matriz)

0.6419890583484975

In [45]:
# media de todos los elementos

matriz.mean()

0.5907254252891814

In [46]:
# media de cada columna

matriz.mean(axis=0)

array([0.45491876, 0.75075926, 0.56649825])

In [47]:
# desviación estándar de todos los elementos

matriz.std()

0.3037002975997723

In [48]:
# desviación estándar de cada columna

matriz.std(axis=0)

array([0.34434296, 0.23669433, 0.2397167 ])

In [49]:
# varianza de todos los elementos

matriz.var()

0.09223387076219026

In [50]:
# varianza de cada columna
    
matriz.var(axis=0)

array([0.11857207, 0.0560242 , 0.0574641 ])

In [ ]:
 # desviación estándar de todos los elementos

In [51]:
matriz.var()**0.5

0.3037002975997723

In [52]:
# suma elemento a elemento  (element wise)

np.add(matriz[0], matriz[1])

array([1.39611069, 1.31716457, 1.13573315])

In [53]:
# resta elemento a elemento

np.subtract(matriz[0], matriz[1])

array([-0.32130043,  0.66931604,  0.14824497])

In [54]:
# multiplica todos los elementos entre si

np.prod(matriz)

5.2098271887666246e-06

In [55]:
# notación científica

1e3   # 1000

1000.0

In [56]:
1e-3

0.001

In [57]:
# multiplica dos vectores elemento a elemento

np.multiply(matriz[0], matriz[1])

array([0.46147277, 0.32173463, 0.3169783 ])

In [58]:
# producto escalar (resultado es un numero), dot product, inner product

np.dot(matriz[0], matriz[1])

1.1001857098005137

In [59]:
 # producto vectorial (maximo 3 dim)

np.cross(matriz[0], matriz[1])

array([ 0.2824507 ,  0.28593897, -0.67882242])

In [60]:
 # matriz traspuesta
    
matriz.T

array([[0.53740513, 0.85870556, 0.77147219, 0.06995627, 0.03705467],
       [0.99324031, 0.32392426, 0.92498922, 0.8218838 , 0.68975874],
       [0.64198906, 0.49374409, 0.94697844, 0.54538279, 0.20439685]])

In [61]:
matriz.transpose()

array([[0.53740513, 0.85870556, 0.77147219, 0.06995627, 0.03705467],
       [0.99324031, 0.32392426, 0.92498922, 0.8218838 , 0.68975874],
       [0.64198906, 0.49374409, 0.94697844, 0.54538279, 0.20439685]])

In [62]:
# multiplicación de matrices

np.matmul(matriz, matriz)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 3)

In [ ]:
 # error de dimensiones

In [63]:
np.matmul(matriz, matriz.T)

array([[1.68748053, 1.10018571, 1.94127949, 1.20405275, 0.83623009],
       [1.10018571, 1.0860854 , 1.42965892, 0.59557947, 0.35616838],
       [1.94127949, 1.42965892, 2.34754257, 1.33066872, 0.86016546],
       [1.20405275, 0.59557947, 1.33066872, 0.97782924, 0.68096826],
       [0.83623009, 0.35616838, 0.86016546, 0.68096826, 0.51891824]])

In [64]:
# producto tensorial

np.tensordot(matriz, matriz)

array(6.61785598)

In [65]:
# sumatorio, suma acumulada

np.cumsum(matriz)

array([0.53740513, 1.53064543, 2.17263449, 3.03134006, 3.35526432,
       3.84900841, 4.62048059, 5.54546982, 6.49244826, 6.56240453,
       7.38428832, 7.92967112, 7.96672579, 8.65648453, 8.86088138])

In [66]:
# productorio, producto acumulado

np.cumprod(matriz)

array([5.37405129e-01, 5.33772435e-01, 3.42676063e-01, 2.94257842e-01,
       9.53172538e-02, 4.70623308e-02, 3.63072792e-02, 3.35838420e-02,
       3.18031745e-02, 2.22483134e-03, 1.82855283e-03, 9.97261250e-04,
       3.69531872e-05, 2.54887837e-05, 5.20982719e-06])

In [67]:
np.inf

inf

In [68]:
np.nan

nan